### ISSUE TITLE
Greg figures out how to use issues template

### ISSUE THREAD

**Issue by gregwilliamsnoaa** [nmfs-openscapes/2022-noaa-nwfsc-fall#16]
Here's my imaginary list

1. Create deadline table
2. Assign files to each
3. Who?

- [x] Greg @gregwilliamsnoaa 
- [ ] Michelle @michellesculley 
- [ ] Kelly @kellyandrews

**Comment by k-doering-NOAA** [comment]
Hi @gregwilliamsnoaa !
