### ISSUE TITLE
Adding tasks in issues to projects.

### ISSUE THREAD

**Issue by michellesculley** [nmfs-openscapes/2022-noaa-nwfsc-fall#7]
If I make a list of tasks in an issue, and link it to a project. When I click the checkmark box, does it move the task to done in my project as well?

- [x] Let's fine out
- [x] With a list of tags
- [x] Hyena in an elevator

**Comment by stefaniebutland** [comment]
> When I click the checkmark box, does it move the task to done in my project as well?

Let us know if you get an answer!

**Comment by eeholmes** [comment]
Similar to #16

**Comment by michellesculley** [comment]
Looks like it does not. It will move it to done if you close the issue (and have it set up that way in your project). But not if you just mark the tasks as done.
